name: 'Gradle Dependency Submission'
description: 'Calculates dependencies for a Gradle build-target and submits the list to the Dependency Submission API'
author: 'Mike Penz'
branding:
  icon: 'check-circle'  
  color: 'blue'
inputs:
  token:
    description: "GitHub Personal Access Token (PAT). Defaults to PAT provided by Action runner"
    required: false
    default: ${{ github.token }}
  use-gradlew:
    required: true
    description: 'Describes if the action will use `./gradlew` to retrieve the dependencies. Alternative `gradle`'
    default: 'true'
  gradle-project-path:
    required: true
    description: 'Path to the root of the project to extract dependencies for'
    default: ''
  gradle-build-module:
    required: true
    description: 'The module for which to resolve dependencies. E.g. `:app`'
    default: ''
  gradle-build-configuration:
    required: true
    description: 'The configuration used to retrieve all dependencies from.'
    default: 'debugCompileClasspath'
  gradle-dependency-path:
    required: false
    description: 'Path to the file containing the dependency specification. Relative to the provided project-path. By default it will retrieve this via gradle.'
runs:
  using: 'node16'
  main: 'dist/index.js'
