name: 'gradle-dependency-submission'
description: 'Calculates dependencies for a Gradle build-target and submits the list to the Dependency Submission API'
author: 'Mike Penz'
inputs:
  token:
    description: "GitHub Personal Access Token (PAT). Defaults to PAT provided by Action runner"
    required: false
    default: ${{ github.token }}
  metadata:
    required: false
    description: 'User provided map of max key/value pairs of metadata to include with the snapshot e.g. {"lastModified": "12-31-2022"}'
  gradle-project-path:
    required: true
    description: 'Path to the root of the project to extract dependencies for'
    default: ''
  gradle-dependency-path:
    required: true
    description: 'Path to the file containing the dependency specification. Relative to the provided project-path. Defaults to the root `build.gradle`'
    default: 'build.gradle'
  gradle-build-module:
    required: true
    description: 'The module for which to resolve dependencies. E.g. `:app`'
    default: ''
  gradle-build-configuration:
    required: true
    description: 'The configuration used to retrieve all dependencies from.'
    default: 'debugCompileClasspath'
runs:
  using: 'node16'
  main: 'dist/index.js'
